title: Affiliate
description: Quickly add affiliate links onto your website.
show_downloads: true
google_analytics: UA-72546719-11
theme: jekyll-theme-cayman
author: Russell Steadman
author_email: e8a7d812@opayq.com